name: Documentation

on:
  push:
    branches: [rolling]
  workflow_dispatch:

jobs:
  build_documentation:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - uses: actions/checkout@v4

      # Étape 2 : Installer Python et pip
      - name: Install Python and pip
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq python3 python3-pip python3-venv
          python3 --version
          pip3 --version

      # Étape 3 : Vérifier la structure des dossiers
      - name: Verify conf.py presence
        run: |
          cd ./doc/sphinx/source/
          ls -la

      # Étape 4 : Créer un environnement virtuel et installer les dépendances
      - name: Create virtual environment and install Sphinx
        run: |
          cd ./doc/sphinx/
          python3 -m venv .venv
          .venv/bin/python3 -m pip install --upgrade pip
          .venv/bin/python3 -m pip install sphinx
          .venv/bin/python3 -m pip install -r ./source/requirements.txt

      # Étape 5 : Construire la documentation
      - name: Build documentation
        run: |
          cd ./doc/sphinx/
          .venv/bin/python3 -m sphinx -b html ./source ./build/html

      # Étape 6 : Déployer sur gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./doc/sphinx/build/html
