name: Documentation

on:
  push:
    branches: [rolling]
  workflow_dispatch:

jobs:
  build_documentation:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - uses: actions/checkout@v4

      # Étape 2 : Installer Python et pip
      - name: Install Python and pip
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq python3 python3-pip python3-venv
          python3 --version
          pip3 --version

      # Étape 3 : Vérifier la structure des dossiers
      - name: Verify conf.py presence
        run: |
          cd ./doc/sphinx/
          ls -la

      # Étape 4 : Créer un environnement virtuel et installer les dépendances
      - name: Create virtual environment and install Sphinx
        run: |
          cd ./doc/sphinx/
          python3 -m venv .venv
          .venv/bin/python3 -m pip install --upgrade pip
          .venv/bin/python3 -m pip install sphinx
          .venv/bin/python3 -m pip install -r requirements.txt

      # Étape 5 : Construire la documentation
      - name: Build documentation
        run: |
          cd ./doc/sphinx/
          .venv/bin/python3 -m sphinx -b html ./source ./build/html

      # Étape 6 : Mettre à jour la branche gh-pages
      - name: Update gh-pages branch
        run: |
          git clone https://github.com/gregowa/info_indus_tutorial.git --branch gh-pages --single-branch gh-pages
          mkdir -p gh-pages/docs/
          cp -r ./doc/sphinx/build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          touch .nojekyll
          git add .
          git commit -m "Update documentation" -a || true
          git push origin gh-pages
