name: Documentation

on:
  push:
    branches: [rolling]
  workflow_dispatch:

jobs:
  build_documentation:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - uses: actions/checkout@v4

      # Étape 2 : Vérifier et installer les dépendances nécessaires
      - name: Install Python and dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq python3 python3-pip python3-venv
          python3 --version
          pip --version

      # Étape 3 : Vérifier les permissions et le système de fichiers
      - name: Check system environment
        run: |
          which python3
          which pip
          python3 -m ensurepip
          ls -l /usr/bin/python3
          ls -l /usr/bin/pip3

      # Étape 4 : Créer un environnement virtuel et installer les dépendances Sphinx
      - name: Create virtual environment and install Sphinx
        run: |
          cd ./doc/sphinx/
          python3 -m venv .venv
          ls -l .venv/bin  # Vérification des fichiers dans l'environnement virtuel
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt || echo "Error installing requirements.txt"

      # Étape 5 : Construire la documentation avec Sphinx
      - name: Build documentation
        run: |
          cd ./doc/sphinx/
          source .venv/bin/activate
          sphinx-build -b html . ./build/html

      # Étape 6 : Cloner la branche gh-pages et mettre à jour la documentation
      - name: Update gh-pages branch
        run: |
          git clone https://github.com/gregowa/info_indus_tutorial.git --branch gh-pages --single-branch gh-pages
          mkdir -p gh-pages/docs/
          cp -r ./doc/sphinx/build/html/* gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          touch .nojekyll
          git add .
          git commit -m "Update documentation" -a || true
          git push origin gh-pages
